language: node_js
node_js:
  - 14
cache:
  - npm

# install:
#   - npm install

script:
  - npm run start

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: Backend/app.js
  on:
    branch: main
